name: tryon-adapter
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
      - absl-py==2.3.0
      - accelerate==1.0.1
      - addict==2.4.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.8
      - async-timeout==5.0.1
      - attrs==25.3.0
      - basicsr==1.4.2
      - cachetools==5.5.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - diffusers==0.14.0
      - einops==0.3.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - ftfy==6.2.3
      - future==1.0.0
      - google-auth==2.40.2
      - google-auth-oauthlib==1.0.0
      - grpcio==1.70.0
      - hf-xet==1.1.2
      - huggingface-hub==0.25.0
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - kornia==0.6.0
      - lazy-loader==0.4
      - lightning-utilities==0.11.9
      - lmdb==1.6.2
      - markdown==3.7
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - multidict==6.1.0
      - networkx==3.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - omegaconf==2.1.1
      - opencv-python==4.1.2.30
      - packaging==25.0
      - pandas==2.0.3
      - pillow==9.5.0
      - platformdirs==4.3.6
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydeprecate==0.3.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.4.2
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - safetensors==0.5.3
      - scikit-image==0.21.0
      - scipy==1.10.1
      - tb-nightly==2.14.0a20230808
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - test-tube==0.7.5
      - tifffile==2023.7.10
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torchgeometry==0.1.2
      - torchmetrics==0.6.0
      - tqdm==4.67.1
      - transformers==4.46.3
      - tzdata==2025.2
      - wcwidth==0.2.13
      - werkzeug==3.0.6
      - yapf==0.43.0
      - yarl==1.15.2
      - zipp==3.20.2
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e git+https://github.com/openai/CLIP.git@main#egg=clip
